ttruck/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ttruckapp.urls', namespace='ttruckapp')),
]

ttruckapp/urls.py
from django.urls import path
from ttruckapp import views


app_name = 'ttruckapp'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('form/', views.purchase_form, name='form'),
    path('package_orders/', views.package_orders, name='package_orders'),
    path('package_product_purchases/', views.package_product_purchases,
         name='package_product_purchases'),
    path('product_orders/', views.product_orders, name='product_orders'),
    path('product_purchases/', views.product_purchases, name='product_purchases'),

    path('package_products/', views.package_products, name='package_products'),
    path('packages/', views.packages, name='packages'),
    path('product_categorys/', views.product_categorys, name='product_categorys'),
    path('product_package_price_historys/', views.product_package_price_historys,
         name='product_package_price_historys'),
    path('products/', views.products, name='products'),

    path('blog_posts/', views.blog_posts, name='blog_posts'),
    path('email_otps/', views.email_otps, name='email_otps'),
    path('profiles/', views.profiles, name='profiles'),
    path('user_notifications/', views.user_notifications,
         name='user_notifications'),
    path('users/', views.users, name='users'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    {% block navbar %}
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

.navbar {
  overflow: hidden;
  background-color: red; 
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.subnav {
  float: left;
  overflow: hidden;
}

.subnav .subnavbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .subnav:hover .subnavbtn {
  background-color: black;
}

.subnav-content {
  display: none;
  position: absolute;
  left: 0;
  background-color: black;
  width: 100%;
  z-index: 1;
}

.subnav-content a {
  float: left;
  color: white;
  text-decoration: none;
}

.subnav-content a:hover {
  background-color: red;
  color: whites;
}

.subnav:hover .subnav-content {
  display: block;
}
</style>

<div class="navbar">
  <a href="{% url 'ttruckapp:home' %}">Home</a>
  
  <div class="subnav">
    <button class="subnavbtn">Purchase <i class="fa fa-caret-down"></i>       		</button>
    <div class="subnav-content">
      <a href="{% url 'ttruckapp:package_orders' %}">Package orders</a>
      <a href="{% url 'ttruckapp:package_product_purchases' %}">Package product purchases</a>
      <a href="{% url 'ttruckapp:product_orders' %}">Product orders</a>
      <a href="{% url 'ttruckapp:product_purchases' %}">Product purchases</a>
    </div>
  </div> 
  
  
  <div class="subnav">
    <button class="subnavbtn">Services <i class="fa fa-caret-down"></i>		     </button>
    <div class="subnav-content">
      <a href="{% url 'ttruckapp:package_products' %}">Package products</a>
      <a href="{% url 'ttruckapp:packages' %}">Packages</a>
      <a href="{% url 'ttruckapp:product_categorys' %}">Product categorys</a>
      <a href="{% url 'ttruckapp:product_package_price_historys' %}">Product package price historys</a>
      <a href="{% url 'ttruckapp:products' %}">Products</a>
      
    </div>
  </div> 
  
  
  <div class="subnav">
    <button class="subnavbtn">Useraccount <i class="fa fa-caret-down"></i>			</button>
    <div class="subnav-content">
      <a href="{% url 'ttruckapp:blog_posts' %}">Blog posts</a>
      <a href="{% url 'ttruckapp:email_otps' %}">Email otps</a>
      <a href="{% url 'ttruckapp:profiles' %}">Profiles</a>
      <a href="{% url 'ttruckapp:user_notifications' %}">User notifications</a>
      <a href="{% url 'ttruckapp:users' %}">Users</a>
      
    </div>
  </div>
  <a href="{% url 'ttruckapp:form' %}">Add</a>
</div>

    {% endblock navbar%}





    {% block content %}
    {% endblock content %}
</body>
</html>